### ISSUE TITLE
Math expressions in markdown

### ISSUE THREAD

**Issue by g-dyer** [Studiobear/snowpack-plugin-mdsvex#8]
How do you configure this plugin to process math expressions embedded in the markdown using katex?

**Comment by bearcanrun** [comment]
My apologies for not seeing you question sooner. However, I am closing this issue as I'll be archiving this library again. This plugin was created in anticipation of Svelte Kit, but in the end the SvelteJS moved away [from Snowpack to Vite](https://svelte.dev/blog/sveltekit-beta).
